module.exports = {
  CONNECTION: "connection",
  DISCONNECTION: "disconnect",
  JOIN: "join",
  BYE: "bye",
  USER_JOINED: "user joined",
  USER_LEFT: "user left",
  RECEIVE_PARTICIPANTS: "receive participants",
  RECEIVE_ACTIVE_ROOM_LIST: "receive active room list",
  RECEIVE_TARGET_ROOM_INFO: "receive target room info",
  INIT_ROOM_LIST: "init room list",
  CREATE_ROOM: "create room",
  SENDING_SIGNAL: "sending signal",
  RETURNING_SIGNAL: "returning signal",
  RECEIVE_RETURNED_SIGNAL: "receiving returned signal",
  SEND_CHAT: "send chat",
  RECEIVE_CHAT: "receive chat",
  RECEIVE_TEXT: "receive text",
  START_TYPING: "start typing",
  STOP_TYPING: "stop typing",
  RECEIVE_FILTERED_USER_LIST: "receive filtered user list",
  RECEIVE_DOCUMENT_TEXT: "receive document text",
  SET_CONTENTS: "set contents",
  SET_INITIAL_TEXT: "set initial text",
  RECEIVE_INITIAL_TEXT: "receive initial text",
  SEND_DRAW_START: "send draw start",
  DRAW_START: "draw start",
  SEND_DRAW: "send draw",
  DRAWING: "drawing",
  DELETE_CANVAS: "delete canvas",
  CLEAR_CANVAS: "clear canvas",
  CHANGE_COLOR: "change color",
  RECEIVE_COLOR: "receive color",
  VIDEO_TOGGLE: "video toggle"
};
