module.exports = [
  {
    action: "2손가락 왼쪽 슬라이드",
    function: "goBackInBrowser",
    description: "이전페이지로",
    direction: "left",
    position: "x",
    pointer: 2,
    count: 0,
  },
  {
    action: "2손가락 오른쪽 슬라이드",
    function: "goForwardInBrowser",
    description: "다음페이지로",
    direction: "right",
    position: "x",
    pointer: 2,
    count: 0,
  },
  {
    action: "2손가락 탭",
    function: "rightClick",
    description: "오른쪽 클릭",
    direction: "tap",
    pointer: 2,
    count: 0,
  },
  {
    action: "4손가락 왼쪽 슬라이드",
    function: "goBackInTap",
    description: "이전 탭으로",
    direction: "left",
    position: "x",
    pointer: 4,
    count: 0,
  },
  {
    action: "4손가락 오른쪽 슬라이드",
    function: "goForwardInTap",
    description: "다음 탭으로",
    direction: "right",
    position: "x",
    pointer: 4,
    count: 0,
  },
];
