const PRIMARY_BLUE = "#283593";
const SECONDARY_BLUE = "#234DC4";

const PRIMARY_GRAY = "#B0BEC5";
const SECONDARY_GRAY = "#EBEFF5";

const PRIMARY_WHITE = "#F6F6F6";
const SECONDARY_WHITE = "#FFFFFF";

const PRIMARY_YELLOW = "#FDF3A7";

const PRIMARY_MODAL = "rgba(0, 0, 0, 0.2)";
const PRIMARY_SHADOW = "rgb(50, 50, 50)";

export {
  PRIMARY_BLUE,
  SECONDARY_BLUE,

  PRIMARY_GRAY,
  SECONDARY_GRAY,

  PRIMARY_WHITE,
  SECONDARY_WHITE,

  PRIMARY_YELLOW,

  PRIMARY_MODAL,
  PRIMARY_SHADOW,
};
