import * as device from "./device";

const DEVICE_WIDTH = device.WIDTH;
const DEVICE_HEIGHT = device.HEIGHT;

const PRIMARY_FONT_SIZE = 24;
const SECONDARY_FONT_SIZE = 18;
const TERTIARY_FONT_SIZE = 16;
const QUATERNARY_FONT_SIZE = 14;
const QUINARY_FONT_SIZE = 12;

const HEADER_HEIGHT = 80;
const HEAADER_FONT_SIZE = 30;

export {
  DEVICE_WIDTH,
  DEVICE_HEIGHT,

  PRIMARY_FONT_SIZE,
  SECONDARY_FONT_SIZE,
  TERTIARY_FONT_SIZE,
  QUATERNARY_FONT_SIZE,
  QUINARY_FONT_SIZE,

  HEADER_HEIGHT,
  HEAADER_FONT_SIZE,
};
