export const RECEIVE_BOOKMARK = 'RECEIVE_BOOKMARK';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export const RECEIVE_IMAGE_DATA = 'RECEIVE_IMAGE_DATA';
export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA';
export const RECEIVE_DETECTED_TEXT = 'RECEIVE_DETECTED_TEXT';

export const SELECTED_BOOK = 'SELECTED_BOOK';
export const EDIT_MODE_DATA = 'EDIT_MODE_DATA';
export const SELECTED_BOOK_IN_EDIT_MODE = 'SELECTED_BOOK_IN_EDIT_MODE';
export const CHANGED_IMAGE_IN_EDIT_MODE = 'CHANGED_IMAGE_IN_EDIT_MODE';

export const BY_USER_PREFERENCE = 'BY_USER_PREFERENCE';
export const DISPATCH_BOOKREPORT_DATA = 'DISPATCH_BOOKREPORT_DATA';

export const DRAFTS = 'DRAFTS';
export const CLEAR_DRAFTS = 'CLEAR_DRAFTS';
export const DRAFTS_IMAGE = 'DRAFTS_IMAGE';
