/* AUTH ACTIONS */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

/* USER ACTIONS */
export const GET_ARTISTS_REQUEST = 'GET_ARTISTS_REQUEST';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_FAILED = 'GET_ARTISTS_FAILED';
export const SELECT_FAVORITE_ARTIST = 'SELECT_FAVORITE_ARTIST';
export const DESELECT_FAVORITE_ARTIST = 'DESELECT_FAVORITE_ARTIST';
export const SAVE_ARTISTS_REQUEST = 'SAVE_ARTISTS_REQUEST';
export const SAVE_ARTISTS_SUCCESS = 'SAVE_ARTISTS_SUCCESS';
export const SAVE_ARTISTS_FAILED = 'SAVE_ARTISTS_FAILED';
export const CLEAR_POST_RESULT = 'CLEAR_POST_RESULT';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

/* WAITING ACTIONS */
export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE';
export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILED = 'CREATE_GAME_FAILED';
export const JOIN_GAME_REQUEST = 'JOIN_GAME_REQUEST';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAILED = 'JOIN_GAME_FAILED';
export const CLAER_CREATE_GAME_ERROR = 'CLAER_CREATE_GAME_ERROR';

/* GAME ACTIONS */
export const UPDATE_GAME_HOST = 'UPDATE_GAME_HOST';
export const UPDATE_PLAYERS_AND_READY_STATUS = 'UPDATE_PLAYERS_AND_READY_STATUS';
export const UPDATE_READY_STATUS = 'UPDATE_READY_STATUS';
export const UPDATE_CHAT_MESSAGES = 'UPDATE_CHAT_MESSAGES';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const UPDATE_CURRENT_TRACK = 'UPDATE_CURRENT_TRACK';
export const UPDATE_SCORE_AND_PLAYLOG = 'UPDATE_SCORE_AND_PLAYLOG';
export const UPDATE_PLAYLOG = 'UPDATE_PLAYLOG';
export const UPDATE_GAMESTATE_TO_END = 'UPDATE_GAMESTATE_TO_END';
export const RESET_GAME_STATE = 'RESET_GAME_STATE';
export const DELETE_FAVORITE_TRACK = 'DELETE_FAVORITE_TRACK';

export const FADEOUT_DURATION = 5;
export const TRACK_FADEOUT_SECONDS = 25;
export const TRACK_STOP_SECONDS = 30;
