module.exports = {
  'Australia': '호주',
  'Austria': '오스트리아',
  'Belgium': '벨기에',
  'Canada': '캐나다',
  'Chile': '칠레',
  'China': '중국',
  'Colombia': '콜롬비아',
  'Czechia': '체코',
  'Denmark': '덴마크',
  'Estonia': '에스토니아',
  'Finland': '핀란드',
  'France': '프랑스',
  'Germany': '독일',
  'Greece': '그리스',
  'Hungary': '헝가리',
  'Iceland': '아이슬란드',
  'Ireland': '아일랜드',
  'Israel': '이스라엘',
  'Italy': '이탈리아',
  'Japan': '일본',
  'South Korea': '대한민국',
  'Latvia': '라트비아',
  'Lithuania': '리투아니아',
  'Luxembourg': '룩셈부르크',
  'Mexico': '멕시코',
  'Netherlands': '네덜란드',
  'New Zealand': '뉴질랜드',
  'Norway': '노르웨이',
  'Poland': '폴란드',
  'Portugal': '포르투갈',
  'Slovakia': '슬로바키아',
  'Slovenia': '슬로베니아',
  'Spain': '스페인',
  'Sweden': '스웨덴',
  'Switzerland': '스위스',
  'Turkey': '터키',
  'United Kingdom': '영국',
  'United States of America': '미국',
};
