branch-defaults:
  master:
    environment: Streetcat-development
environment-defaults:
  Streetcat-development:
    branch: null
    repository: null
global:
  application_name: Streetcat
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
