export const DELETE_ROOM = "DELETE_ROOM";
export const SET_ROOM_INFO = "SET_ROOM_INFO";
export const RECEIVE_CHAT = "RECEIVE_CHAT";
export const RECEIVE_DOCUMENT_TEXT = "RECEIVE_DOCUMENT_TEXT";
export const SET_ROOM_LIST = "SET_ROOM_LIST";
export const LEAVE_ROOM = "LEAVE_ROOM";
export const RECEIVE_EDITOR_TYPING_INFO = "RECEIVE_EDITOR_TYPING_INFO";
export const RECEIVE_EDITOR_TYPING_USERS = "RECEIVE_EDITOR_TYPING_USERS";
export const LEAVE_OWNER_ROOM = "LEAVE_OWNER_ROOM";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
