const INITIALIZE_APP_SUCCESS = "INITIALIZE_APP_SUCCESS";
const INITIALIZE_APP_FAIL = "INITIALIZE_APP_FAIL";
const SET_MESSAGE_FILTER = "SET_MESSAGE_FILTER";
const LOAD_MATCH_SUCCESS = "LOAD_MATCH_SUCCESS";
const LOAD_MATCH_FAIL = "LOAD_MATCH_FAIL";
const LOAD_PLAYGROUNDS_SUCCESS = "LOAD_PLAYGROUNDS_SUCCESS";
const LOAD_PLAYGROUNDS_FAIL = "LOAD_PLAYGROUNDS_FAIL";
const LOAD_MY_TEAM_SUCCESS = "LOAD_MY_TEAM_SUCCESS";
const LOAD_MY_TEAM_FAIL = "LOAD_MY_TEAM_FAIL";
const LOAD_TEAM_SUCCESS = "LOAD_TEAM_SUCCESS";
const LOAD_TEAM_FAIL = "LOAD_TEAM_FAIL";

const SET_INITIALIZE_ERROR = "SET_INITIALIZE_ERROR";
const SET_TEAM_EXIST_ERROR = "SET_TEAM_EXIST_ERROR";

const VIEW_LOGIN_REQUEST = "VIEW_LOGIN_REQUEST";
const HIDE_LOGIN_REQUEST = "HIDE_LOGIN_REQUEST";
const VIEW_INPUT_ALERT = "VIEW_INPUT_ALERT";
const HIDE_INPUT_ALERT = "HIDE_INPUT_ALERT";
const VIEW_MATCH_LOADING = "VIEW_MATCH_LOADING";
const HIDE_MATCH_LOADING = "HIDE_MATCH_LOADING";
const VIEW_RANK_LOADING = "VIEW_RANK_LOADING";
const HIDE_RANK_LOADING = "HIDE_RANK_LOADING";
const VIEW_MESSAGE_LOADING = "VIEW_MESSAGE_LOADING";
const HIDE_MESSAGE_LOADING = "HIDE_MESSAGE_LOADING";
const VIEW_HEADER_RIGHT_LOADING = "VIEW_HEADER_RIGHT_LOADING";
const HIDE_HEADER_RIGHT_LOADING = "HIDE_HEADER_RIGHT_LOADING";
const VIEW_COMPLETION = "VIEW_COMPLETION";
const HIDE_COMPLETION = "HIDE_COMPLETION";

const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const SET_CURRENT_TEAM = "SET_CURRENT_TEAM";
const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
const SET_CURRENT_SPORTS = "SET_CURRENT_SPORTS";
const LOAD_MY_MESSAGE_SUCCESS = "LOAD_MY_MESSAGE_SUCCESS";
const LOAD_MY_MESSAGE_FAIL = "LOAD_MY_MESSAGE_FAIL";
const SAVE_MY_LOCATION_SUCCESS = "SAVE_MY_LOCATION_SUCCESS";
const UPDATE_MY_DATA_FAIL = "UPDATE_MY_DATA_FAIL";
const UPDATE_MY_DATA_SUCCESS = "UPDATE_MY_DATA_SUCCESS";

export {
  SET_MESSAGE_FILTER,
  INITIALIZE_APP_SUCCESS,
  INITIALIZE_APP_FAIL,
  LOAD_MATCH_SUCCESS,
  LOAD_MATCH_FAIL,
  LOAD_PLAYGROUNDS_SUCCESS,
  LOAD_PLAYGROUNDS_FAIL,
  LOAD_MY_TEAM_SUCCESS,
  LOAD_MY_TEAM_FAIL,
  LOAD_TEAM_SUCCESS,
  LOAD_TEAM_FAIL,

  SET_INITIALIZE_ERROR,
  SET_TEAM_EXIST_ERROR,

  VIEW_LOGIN_REQUEST,
  HIDE_LOGIN_REQUEST,
  VIEW_INPUT_ALERT,
  HIDE_INPUT_ALERT,
  VIEW_MATCH_LOADING,
  HIDE_MATCH_LOADING,
  VIEW_RANK_LOADING,
  HIDE_RANK_LOADING,
  VIEW_MESSAGE_LOADING,
  HIDE_MESSAGE_LOADING,
  VIEW_HEADER_RIGHT_LOADING,
  HIDE_HEADER_RIGHT_LOADING,
  VIEW_COMPLETION,
  HIDE_COMPLETION,

  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAIL,
  AUTH_LOGOUT,
  SET_CURRENT_TEAM,
  SET_CURRENT_LOCATION,
  SET_CURRENT_SPORTS,
  LOAD_MY_MESSAGE_SUCCESS,
  LOAD_MY_MESSAGE_FAIL,
  SAVE_MY_LOCATION_SUCCESS,
  UPDATE_MY_DATA_FAIL,
  UPDATE_MY_DATA_SUCCESS,
};
