export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const CHECK_USER = "CHECK_USER";
export const EXPIRED_TOKEN = "EXPIRED_TOKEN";
export const UPDATE_MONEY = "UPDATE_MONEY";
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";

export const FETCH_TODAY_GAME_SCHEDULE = "FETCH_TODAY_GAME_SCHEDULE";
export const FETCH_USER_RANKINGS = "FETCH_USER_RANKINGS";
export const FETCH_PLAYER_RANKINGS = "FETCH_PLAYER_RANKINGS";

export const CATCH_API_ERROR = "CATCH_API_ERROR";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
