branch-defaults:
  default:
    environment: Server-env
    group_suffix: null
global:
  application_name: server
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
