export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const COUNT_PHOTO = 'COUNT_PHOTO';
export const DECOUNT_PHOTO = 'DECOUNT_PHOTO';
export const DELETE_SELECTED_PHOTOS = 'DELETE_SELETED_PHOTOS';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_PHOTOS_DATA = 'SET_PHOTOS_DATA';
export const SET_PHOTOS_FOCUS = 'SET_PHOTOS_FOCUS';
