exports.PORTFOLIO_LIST = [
  "DragonFly Capital Portfolio",
  "Fenbushi Capital Portfolio",
  "1Confirmation Portfolio",
  "Galaxy Digital Portfolio",
  "Blockchain Capital Portfolio",
  "Fabric Ventures Portfolio",
  "LedgerPrime Portfolio",
  "BoostVC Portfolio",
  "USV Portfolio",
  "DCG Portfolio",
  "Polychain Capital Portfolio",
  "Pantera Capital Portfolio",
  "Alameda Research Portfolio",
  "Binance Labs Portfolio",
  "Hashkey Capital Portfolio",
  "Multicoin Capital Portfolio",
  "Placeholder Ventures Portfolio",
  "Three Arrows Capital Portfolio",
  "CMS Holdings Portfolio",
  "A16Z Portfolio",
  "electric-capital-portfolio",
  "Exnetwork Capital Portfolio",
  "Coinbase Ventures Portfolio",
  "Coinfund Portfolio",
];

exports.PORTFOLIO_DATA = {
  "DragonFly Capital Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Cosmos",
      "Maker",
      "Avalanche",
      "Compound",
      "Siacoin",
      "UMA",
      "Celo",
      "1inch",
      "Nervos Network",
      "Nebulas",
    ],
    ticker: [
      "BTC",
      "ETH",
      "ATOM",
      "MKR",
      "AVAX",
      "COMP",
      "SC",
      "UMA",
      "CELO",
      "1INCH",
      "CKB",
      "NAS",
    ],
  },
  "Fenbushi Capital Portfolio": {
    name: [
      "Polkadot",
      "VeChain",
      "EOS",
      "Zcash",
      "Siacoin",
      "Ripio Credit Network",
      "Tierion",
      "Factom",
      "TenX",
    ],
    ticker: ["DOT", "VET", "EOS", "ZEC", "SC", "RCN", "TNT", "FCT", "PAY"],
  },
  "1Confirmation Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Cosmos",
      "Maker",
      "Kusama",
      "Basic Attention Token",
      "Nervos Network",
      "Augur",
    ],
    ticker: ["BTC", "ETH", "DOT", "ATOM", "MKR", "KSM", "BAT", "CKB", "REP"],
  },
  "Galaxy Digital Portfolio": {
    name: ["Bitcoin", "XRP", "EOS", "Monero", "SKALE Network", "WAX", "Kin"],
    ticker: ["BTC", "XRP", "EOS", "XMR", "SKL", "WAXP", "KIN"],
  },
  "Blockchain Capital Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Uniswap",
      "Filecoin",
      "Aave",
      "Stacks",
      "SushiSwap",
      "yearn.finance",
      "0x",
      "UMA",
      "1inch",
      "Arweave",
      "Nervos Network",
      "Badger DAO",
      "Orchid",
    ],
    ticker: [
      "BTC",
      "ETH",
      "DOT",
      "UNI",
      "FIL",
      "AAVE",
      "STX",
      "SUSHI",
      "YFI",
      "ZRX",
      "UMA",
      "1INCH",
      "AR",
      "CKB",
      "BADGER",
      "OXT",
    ],
  },
  "Fabric Ventures Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Decentraland",
      "Stacks",
      "The Graph",
      "NEAR Protocol",
      "0x",
      "1inch",
      "Status",
      "Ocean Protocol",
      "Orchid",
      "Keep Network",
      "Streamr",
      "Radicle",
      "Raiden Network Token",
      "Bloom",
    ],
    ticker: [
      "BTC",
      "ETH",
      "DOT",
      "MANA",
      "STX",
      "GRT",
      "NEAR",
      "ZRX",
      "1INCH",
      "SNT",
      "OCEAN",
      "OXT",
      "KEEP",
      "DATA",
      "RAD",
      "RDN",
      "BLT",
    ],
  },
  "LedgerPrime Portfolio": {
    name: [
      "The Graph",
      "Flow",
      "Rally",
      "Akropolis",
      "Hxro",
      "Edgeware",
      "Rari Governance Token",
      "saffron.finance",
      "PowerPool",
      "PowerTrade Fuel",
      "Edgeless",
    ],
    ticker: [
      "GRT",
      "FLOW",
      "RLY",
      "AKRO",
      "HXRO",
      "EDG",
      "RGT",
      "SFI",
      "CVP",
      "PTF",
      "EDG",
    ],
  },
  "BoostVC Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Filecoin",
      "Monero",
      "Tezos",
      "Zcash",
      "Decentraland",
      "0x",
      "SKALE Network",
      "Aragon",
      "Keep Network",
      "Handshake",
      "district0x",
      "Ripio Credit Network",
    ],
    ticker: [
      "BTC",
      "ETH",
      "DOT",
      "FIL",
      "XMR",
      "XTZ",
      "ZEC",
      "MANA",
      "ZRX",
      "SKL",
      "ANT",
      "KEEP",
      "HNS",
      "DNT",
      "RCN",
    ],
  },
  "USV Portfolio": {
    name: ["Bitcoin", "Ethereum", "Algorand", "Stacks", "Helium", "Numeraire"],
    ticker: ["BTC", "ETH", "ALGO", "STX", "HNT", "NMR"],
  },
  "DCG Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Ethereum Classic",
      "Filecoin",
      "Zcash",
      "Hedera Hashgraph",
      "Decentraland",
      "Basic Attention Token",
      "Stacks",
      "The Graph",
      "Horizen",
      "Reserve Rights",
      "Flow",
      "Livepeer",
      "Ocean Protocol",
      "Civic",
      "Handshake",
      "API3",
      "Tierion",
      "DECENT",
    ],
    ticker: [
      "BTC",
      "ETH",
      "ETC",
      "FIL",
      "ZEC",
      "HBAR",
      "MANA",
      "BAT",
      "STX",
      "GRT",
      "ZEN",
      "RSR",
      "FLOW",
      "LPT",
      "OCEAN",
      "CVC",
      "HNS",
      "API3",
      "TNT",
      "DCT",
    ],
  },
  "Polychain Capital Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Filecoin",
      "Cosmos",
      "Tezos",
      "Maker",
      "Avalanche",
      "Compound",
      "Zilliqa",
      "yearn.finance",
      "0x",
      "Celo",
      "Nervos Network",
      "NuCypher",
      "Kin",
      "Orchid",
      "Keep Network",
      "Mina",
      "Internet Computer",
    ],
    ticker: [
      "BTC",
      "ETH",
      "DOT",
      "FIL",
      "ATOM",
      "XTZ",
      "MKR",
      "AVAX",
      "COMP",
      "ZIL",
      "YFI",
      "ZRX",
      "CELO",
      "CKB",
      "NU",
      "KIN",
      "OXT",
      "KEEP",
      "MINA",
      "ICP",
    ],
  },
  "Pantera Capital Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "XRP",
      "Polkadot",
      "Uniswap",
      "Filecoin",
      "Terra",
      "Aave",
      "FTX Token",
      "Maker",
      "Compound",
      "Zcash",
      "Basic Attention Token",
      "SushiSwap",
      "ICON",
      "OMG Network",
      "0x",
      "Ankr",
      "Livepeer",
      "Kyber Network Crystal Legacy",
      "Augur",
      "Balancer",
      "Injective Protocol",
      "Origin Protocol",
      "FUNToken",
      "DODO",
      "Civic",
      "Celer Network",
      "Kin",
      "Ampleforth",
      "Mirror Protocol",
      "Audius",
      "Handshake",
      "Thunder Token",
      "API3",
      "Gifto",
      "PowerTrade Fuel",
      "MIR COIN",
      "Enigma",
      "Maecenas",
      "Gems ",
      "Reflexer Ungovernance Token",
      "Bloom",
      "Flexacoin",
      "Kyber Network Crystal v2",
    ],
    ticker: [
      "BTC",
      "ETH",
      "XRP",
      "DOT",
      "UNI",
      "FIL",
      "LUNA",
      "AAVE",
      "FTT",
      "MKR",
      "COMP",
      "ZEC",
      "BAT",
      "SUSHI",
      "ICX",
      "OMG",
      "ZRX",
      "ANKR",
      "LPT",
      "KNC",
      "REP",
      "BAL",
      "INJ",
      "OGN",
      "FUN",
      "DODO",
      "CVC",
      "CELR",
      "KIN",
      "AMPL",
      "MIR",
      "AUDIO",
      "HNS",
      "TT",
      "API3",
      "GTO",
      "PTF",
      "MIR",
      "ENG",
      "ART",
      "GEM",
      "FLX",
      "BLT",
      "FXC",
      "KNC",
    ],
  },
  "Alameda Research Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Binance Coin",
      "Uniswap",
      "Solana",
      "Aave",
      "FTX Token",
      "Huobi Token",
      "Compound",
      "UNUS SED LEO",
      "yearn.finance",
      "SushiSwap",
      "OKB",
      "Synthetix",
      "1inch",
      "Ren",
      "Curve DAO Token",
      "Alpha Finance Lab",
      "Serum",
      "Balancer",
      "Swipe",
      "DODO",
      "Ampleforth",
      "Linear",
      "TomoChain",
      "Perpetual Protocol",
      "RAMP",
      "Akropolis",
      "Hxro",
      "Frontier",
      "Cream Finance",
      "MAPS",
      "APY.Finance",
      "mStable Governance Token: Meta (MTA)",
      "Bao Finance",
      "Pickle Finance",
      "Opium",
      "dHedge DAO",
      "KeeperDAO",
      "Hedget",
      "LINA",
    ],
    ticker: [
      "BTC",
      "ETH",
      "BNB",
      "UNI",
      "SOL",
      "AAVE",
      "FTT",
      "HT",
      "COMP",
      "LEO",
      "YFI",
      "SUSHI",
      "OKB",
      "SNX",
      "1INCH",
      "REN",
      "CRV",
      "ALPHA",
      "SRM",
      "BAL",
      "SXP",
      "DODO",
      "AMPL",
      "LINA",
      "TOMO",
      "PERP",
      "RAMP",
      "AKRO",
      "HXRO",
      "FRONT",
      "CREAM",
      "MAPS",
      "APY",
      "MTA",
      "BAO",
      "PICKLE",
      "OPIUM",
      "DHT",
      "ROOK",
      "HGET",
      "LINA",
    ],
  },
  "Binance Labs Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Terra",
      "Polygon",
      "BitTorrent",
      "Elrond",
      "Harmony",
      "1inch",
      "Kava.io",
      "Swipe",
      "Injective Protocol",
      "WINkLink",
      "Band Protocol",
      "Audius",
      "CertiK",
      "Cred",
      "HOPR",
    ],
    ticker: [
      "BTC",
      "ETH",
      "LUNA",
      "MATIC",
      "BTT",
      "EGLD",
      "ONE",
      "1INCH",
      "KAVA",
      "SXP",
      "INJ",
      "WIN",
      "BAND",
      "AUDIO",
      "CTK",
      "LBA",
      "HOPR",
    ],
  },
  "Hashkey Capital Portfolio": {
    name: [
      "Ethereum",
      "Polkadot",
      "Stellar",
      "Filecoin",
      "Terra",
      "Cosmos",
      "Zcash",
      "Stacks",
      "Harmony",
      "Nervos Network",
      "SKALE Network",
      "IoTeX",
      "Kava.io",
      "Edgeware",
      "Ripio Credit Network",
      "Tierion",
      "Factom",
      "Edgeless",
      "Casper",
    ],
    ticker: [
      "ETH",
      "DOT",
      "XLM",
      "FIL",
      "LUNA",
      "ATOM",
      "ZEC",
      "STX",
      "ONE",
      "CKB",
      "SKL",
      "IOTX",
      "KAVA",
      "EDG",
      "RCN",
      "TNT",
      "FCT",
      "EDG",
      "CSPR",
    ],
  },
  "Multicoin Capital Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Binance Coin",
      "Solana",
      "Huobi Token",
      "Algorand",
      "THORChain",
      "The Graph",
      "Helium",
      "Arweave",
      "Livepeer",
      "Nervos Network",
      "Alpha Finance Lab",
      "Augur",
      "Keep Network",
      "Audius",
      "Perpetual Protocol",
      "Kadena",
      "saffron.finance",
    ],
    ticker: [
      "BTC",
      "ETH",
      "BNB",
      "SOL",
      "HT",
      "ALGO",
      "RUNE",
      "GRT",
      "HNT",
      "AR",
      "LPT",
      "CKB",
      "ALPHA",
      "REP",
      "KEEP",
      "AUDIO",
      "PERP",
      "KDA",
      "SFI",
    ],
  },
  "Placeholder Ventures Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Maker",
      "Zcash",
      "Decred",
      "0x",
      "UMA",
      "Balancer",
      "Aragon",
      "Numeraire",
      "NXM",
      "Enzyme",
      "API3",
      "Radicle",
      "FOAM",
    ],
    ticker: [
      "BTC",
      "ETH",
      "DOT",
      "MKR",
      "ZEC",
      "DCR",
      "ZRX",
      "UMA",
      "BAL",
      "ANT",
      "NMR",
      "NXM",
      "MLN",
      "API3",
      "RAD",
      "FOAM",
    ],
  },
  "Three Arrows Capital Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Uniswap",
      "Aave",
      "Compound",
      "yearn.finance",
      "Synthetix",
      "Kyber Network Crystal Legacy",
      "Balancer",
      "DODO",
      "Perpetual Protocol",
      "Hxro",
      "Switcheo",
      "mStable Governance Token: Meta (MTA)",
      "dHedge DAO",
      "KeeperDAO",
      "Compound Uni",
      "Kyber Network Crystal v2",
    ],
    ticker: [
      "BTC",
      "ETH",
      "DOT",
      "UNI",
      "AAVE",
      "COMP",
      "YFI",
      "SNX",
      "KNC",
      "BAL",
      "DODO",
      "PERP",
      "HXRO",
      "SWTH",
      "MTA",
      "DHT",
      "ROOK",
      "CUNI",
      "KNC",
    ],
  },
  "CMS Holdings Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Polkadot",
      "Solana",
      "FTX Token",
      "Avalanche",
      "Kusama",
      "Nervos Network",
      "Serum",
      "Injective Protocol",
      "DODO",
      "Linear",
      "Perpetual Protocol",
      "Hxro",
      "Bonfida",
      "MAPS",
      "Kylin",
      "Opium",
      "PowerTrade Fuel",
      "Siren",
      "LINA",
    ],
    ticker: [
      "BTC",
      "ETH",
      "DOT",
      "SOL",
      "FTT",
      "AVAX",
      "KSM",
      "CKB",
      "SRM",
      "INJ",
      "DODO",
      "LINA",
      "PERP",
      "HXRO",
      "FIDA",
      "MAPS",
      "KYL",
      "OPIUM",
      "PTF",
      "SI",
      "LINA",
    ],
  },
  "A16Z Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "XRP",
      "Uniswap",
      "Filecoin",
      "Maker",
      "Compound",
      "Celo",
      "Flow",
      "Arweave",
      "Keep Network",
      "Orchid",
      "Handshake",
      "Rally",
    ],
    ticker: [
      "BTC",
      "ETH",
      "XRP",
      "UNI",
      "FIL",
      "MKR",
      "COMP",
      "CELO",
      "FLOW",
      "AR",
      "KEEP",
      "OXT",
      "HNS",
      "RLY",
    ],
  },
  "electric-capital-portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Monero",
      "Maker",
      "Zcash",
      "Elrond",
      "NEAR Protocol",
      "Celo",
      "Nervos Network",
    ],
    ticker: ["BTC", "ETH", "XMR", "MKR", "ZEC", "EGLD", "NEAR", "CELO", "CKB"],
  },
  "Exnetwork Capital Portfolio": {
    name: [
      "Polkadot",
      "Cosmos",
      "FTX Token",
      "Algorand",
      "THORChain",
      "Elrond",
      "Celsius",
      "Reef",
      "Serum",
      "Wootrade",
      "DODO",
      "MyNeighborAlice",
      "ECOMI",
      "Orion Protocol",
      "SuperFarm",
      "Hathor",
      "Polkastarter",
      "DIA",
      "RAMP",
      "Persistence",
      "PAID Network",
      "AllianceBlock",
      "Terra Virtua Kolect",
      "xDai",
      "MANTRA DAO",
      "Bifrost (BFC)",
      "Frontier",
      "BSCPAD",
      "YIELD App",
      "Kylin",
      "AIOZ Network",
      "Frax Share",
      "Finxflo",
      "ZeroSwap",
      "Bridge Mutual",
      "CUDOS",
      "APY.Finance",
      "Stafi",
      "UniLend",
      "RioDeFi",
      "Lattice Token",
      "Plasma Finance",
      "Oddz",
      "Archer DAO Governance Token",
      "Equalizer",
      "ExNetwork Token",
      "LABS Group",
      "APYSwap",
      "Konomi Network",
      "Bonded Finance",
      "Hedget",
      "Tidal Finance",
      "Razor Network",
      "Xend Finance",
      "OIN Finance",
      "AnRKey X",
      "Falconswap",
      "Crowny",
      "Nord Finance",
      "Polkacover",
      "SOTA Finance",
      "Hyve",
      "Open Governance Token",
      "Insured Finance",
      "DeHive",
      "Vortex Defi",
      "KINE",
      "THORChain (ERC20)",
      "Unizen",
      "Stone DeFi",
      "Boson Protocol",
      "Cellframe",
      "MemePad",
      "Splyt",
      "KickPad",
      "DigiCol",
      "Finance.Vote",
      "Beyond Finance",
      "e-Money",
      "UNION Protocol Governance Token",
      "MerchDAO",
      "BotOcean",
      "Fire Protocol",
      "MobiFi",
      "DeFi Wizard",
      "GIVLY Coin",
      "Internet Computer",
    ],
    ticker: [
      "DOT",
      "ATOM",
      "FTT",
      "ALGO",
      "RUNE",
      "EGLD",
      "CEL",
      "REEF",
      "SRM",
      "WOO",
      "DODO",
      "ALICE",
      "OMI",
      "ORN",
      "SUPER",
      "HTR",
      "POLS",
      "DIA",
      "RAMP",
      "XPRT",
      "PAID",
      "ALBT",
      "TVK",
      "STAKE",
      "OM",
      "BFC",
      "FRONT",
      "BSCPAD",
      "YLD",
      "KYL",
      "AIOZ",
      "FXS",
      "FXF",
      "ZEE",
      "BMI",
      "CUDOS",
      "APY",
      "FIS",
      "UFT",
      "RFUEL",
      "LTX",
      "PPAY",
      "ODDZ",
      "ARCH",
      "EQZ",
      "EXNT",
      "LABS",
      "APYS",
      "KONO",
      "BOND",
      "HGET",
      "TIDAL",
      "RAZOR",
      "XEND",
      "OIN",
      "$ANRX",
      "FSW",
      "CRWNY",
      "NORD",
      "CVR",
      "SOTA",
      "HYVE",
      "OPEN",
      "INFI",
      "DHV",
      "VTX",
      "KINE",
      "RUNE",
      "ZCX",
      "STN",
      "BOSON",
      "CELL",
      "MEPAD",
      "SHOPX",
      "KPAD",
      "DGCL",
      "FVT",
      "BYN",
      "NGM",
      "UNN",
      "MRCH",
      "BOTS",
      "FIRE",
      "MoFi",
      "DWZ",
      "GIV",
      "ICP",
    ],
  },
  "Coinbase Ventures Portfolio": {
    name: [
      "Bitcoin",
      "Ethereum",
      "Uniswap",
      "Terra",
      "Polygon",
      "Compound",
      "The Graph",
      "NEAR Protocol",
      "UMA",
      "Celo",
      "Reserve Rights",
      "Flow",
      "Arweave",
      "DODO",
      "Keep Network",
      "Audius",
      "Rally",
      "Edgeware",
      "saffron.finance",
      "Rarible",
      "Edgeless",
      "SmartCoin",
      "Unlock Protocol",
      "Mina",
      "Compound Uni",
    ],
    ticker: [
      "BTC",
      "ETH",
      "UNI",
      "LUNA",
      "MATIC",
      "COMP",
      "GRT",
      "NEAR",
      "UMA",
      "CELO",
      "RSR",
      "FLOW",
      "AR",
      "DODO",
      "KEEP",
      "AUDIO",
      "RLY",
      "EDG",
      "SFI",
      "RARI",
      "EDG",
      "SMC",
      "UDT",
      "MINA",
      "CUNI",
    ],
  },
  "Coinfund Portfolio": {
    name: [
      "Polkadot",
      "The Graph",
      "NEAR Protocol",
      "Flow",
      "Livepeer",
      "Serum",
      "Balancer",
      "Numeraire",
      "NuCypher",
      "Hxro",
      "Kadena",
      "NFTX",
      "API3",
      "Rarible",
    ],
    ticker: [
      "DOT",
      "GRT",
      "NEAR",
      "FLOW",
      "LPT",
      "SRM",
      "BAL",
      "NMR",
      "NU",
      "HXRO",
      "KDA",
      "NFTX",
      "API3",
      "RARI",
    ],
  },
};
