const SOCKET_EVENTS = {
  CONNECT_ERROR: "connect_error",
  CONNECT_FAILED: "connect_failed",
  DISCONNECTING: "disconnecting",
  FULL_ROOM: "full_room",
  INVALID_NICKNAME: "invalid_nickname",
  JOIN_ROOM: "join_room",
  KNOCK: "knock",
  EXIT_ROOM: "exit_room",
  JOINED: "joined",
  NEW_PLAYER: "new_player",
  LET_JOIN: "let_join",
  SIGNAL: "signal",
  CHAT: "chat",
  READY: "ready",
  ALL_READY: "all_ready",
  START: "start",
  START_SELECT: "start_select",
  NEW_SELECTOR: "new_selector",
  COUNTDOWN: "countdown",
  SELECT_SUCCESS: "select_success",
  PLAYER_LEFT: "player_left",
  NEW_LEADER: "new_leader",
  SET_CARDS: "set_cards",
  SELECT_CARD: "select_card",
  GAME_OVER: "game_over",
};

module.exports = SOCKET_EVENTS;
