# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'TexpeechIos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for TexpeechIos

  
  target 'TexpeechIos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  end

  target 'TexpeechIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Database'
pod 'Firebase/Auth', '~> 5.3.0'

 pod 'React', :path => '../node_modules/react-native'
 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

